---
title: "About me"
---

## Experience

Here is a resume of my education and working experiences.

### Working

Since the beggining of my Bachelor I've been involved in different working experiences that have helped shaping my professional and personal vision

#### Journalist - Internship

I just came back from my erasmus in Malagá(Spain)  when I decided I wanted to try a different first experience by choosing an international Magazine in growth, In Trieste Mag, one of the most promising tourism start-ups in Friuli Venezia Giulia. I worked for 6 months at the editorial and creative team related not just to journalism, but to social media processes. I was responsible for understanding and traducing accurate information from the events and regional meetings to produce news in time. On the other hand, I also had the opportunity to participate in multiple edition, filming and storyteling ideas to attract the youth

#### Radio Specialist

From June to August 2022 I was involved in a creative summer camp in USA for children and teens. I had to create, in collaboration with my co-host, a daily programme for 6 to 12 weeks incentiving musical culture and intercultural differences

I provided an experience in which the most important thing was to make the things fun to retain children attention for one hour. I was in charge of choosing musical topics, making conversation, bringing special guests to the room, and teaching how to create a podcast in an easy way for everyone,

The idea of bringing children to the radio felt inspiring. It is the best way to impact in the future adults. From the habits to the genuine interest in the information and being part of the important conversations.

#### University Academic tutor/ monitor

During my bachelor, I worked for about one year in this role.

It was a big challenge for me. I was in charge of teaching to people of my same age or older. I gave study counseling, explained concepts, and helped them make a plan to focus on improvement.

I was helping in Audiovisual, Journalism genres and writing techniques.

### Study

Here is a short overall about my studies:

- Master's degree in International Marketing, Management and Organization at University of Udine(currently enrolled)

- Erasmus, during my bachelor, at Universidad de Malagá, where I focused in Audiovisual, PR and digital marketing 

- Bachelor's degree in Social Communication and Journalism, my last year project was awarded with the Jose Recasens.

## Personal Life

### Sport

I think that sport is very important in the life and helps to develop strength and health. Main sports:

- Run: I'm invested in Strava. Lately, I had found that 20's are the best years to try things out. My advice? Follow the run clubs, it makes it easier for you to respect a routine.

- Dance: I know some people don't think it's a sport. But, I can assure you that five or six hours will make you sweat way more than the gym, if well done.

- Cheerleading: Not like in the american movies. I know you taught about it, but just not. I spent my highschool years trying to memorize dance routines, with one or two jumps or acrobacy included. We made it to the regional every year and nationals once.

### Fashion

I have always been interested in this topic. When I was child I used to dream about the day I would be able to afford all the trendy clothes I wanted. Later, I re-discovered myself, and started trying unconventional styles, in order to find my own style. Still on that mission. On the journey, I found the second hand world and got fascinated by the impact it has.

-   Malaga (Spain): I'm sure that everyone who has done an exchange program (e.g. Erasmus) can agree with me, I Ieft a piece of my heart.

-   Sweden: It took place in my first Erasmus project and helped me to fight my fear for English, besides that I got the chance of meeting people from around Europe full of energy and positivity.

-   Marocco: I've been twice but why talking about the easy time with a touristic tour? Well, my girlfriend and I decided to take a random flight to the most unknown city, Nador, and what an adventure with no data and no local language during Ramadan. It has been a full immersion in the Arabic culture.

-   Houston (USA): I went to a wedding and I had the opportunity to live as a Texan for one week.

### Beer

I want to talk about the real beer: the craft one. I'm a nerd about craft beer, I brew my beer since 10 years ago and I use the BIAP method (Brew In A Pot). I love this hobby because it is a mix of creativity, science, and DIY. But I don't only make it, I also taste it and as a good statistician, I record each one on [Untapped](https://untappd.com/user/Erikdeluca)!
